# Generated by Django 5.2 on 2025-04-29 15:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf_registration',
            fields=[
                ('turf_uuid', models.UUIDField(default=uuid.UUID('fc8344bb-ce28-41b4-953e-3cb8ec8fa374'), primary_key=True, serialize=False)),
                ('turf_id', models.CharField(max_length=20, unique=True)),
                ('turf_name', models.CharField(max_length=100)),
                ('turf_address', models.TextField()),
                ('turf_pincode', models.CharField(max_length=20)),
                ('turf_owner_name', models.CharField(max_length=50)),
                ('turf_email_id', models.EmailField(max_length=254, unique=True)),
                ('turf_mobile_number', models.CharField(max_length=10, unique=True)),
                ('turf_alternate_mobile_number', models.CharField(default='', max_length=10)),
                ('turf_land_line_number', models.CharField(default='', max_length=30)),
                ('turf_images_path', models.TextField()),
                ('turf_username', models.CharField(max_length=20, unique=True)),
                ('turf_password', models.CharField(max_length=128)),
                ('turf_starting_time', models.CharField(default='6 A.M', max_length=10)),
                ('turf_ending_time', models.CharField(default='12 P.M', max_length=10)),
                ('turf_register_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
