# Generated by Django 5.2 on 2025-05-01 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_registration',
            name='turf_images_path',
            field=models.ImageField(upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turf_registration',
            name='turf_uuid',
            field=models.UUIDField(default=uuid.UUID('fc8cf41a-18c1-44d9-a378-30c37b344b24'), primary_key=True, serialize=False),
        ),
    ]
