# Generated by Django 5.2 on 2025-05-01 16:27

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turfs', '0002_alter_turf_registration_turf_images_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_registration',
            name='turf_available_games',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='turf_registration',
            name='turf_uuid',
            field=models.UUIDField(default=uuid.UUID('de954729-84ff-4c97-854e-a2a095eed76c'), primary_key=True, serialize=False),
        ),
    ]
