# Generated by Django 5.2 on 2025-04-27 11:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_signup',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.UUID('2067c26d-01ac-433b-b7f0-d68266cc2032'), primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('mailid', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_signup')),
            ],
        ),
    ]
