# Generated by Django 5.2 on 2025-04-27 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_signup_unique_id_random_token_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_token_generation',
            name='random_token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('dd5ec27b-2729-4481-9b90-b21ae71b92ab'), primary_key=True, serialize=False),
        ),
    ]
