# Generated by Django 5.2 on 2025-04-29 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_random_token_generation_random_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('d8ac83df-e466-46b0-a01d-0a6cf5455de5'), primary_key=True, serialize=False),
        ),
    ]
