# Generated by Django 5.2 on 2025-04-29 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_signup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('419ae1ec-4861-48cb-983d-c2d44b14c0ee'), primary_key=True, serialize=False),
        ),
    ]
