# Generated by Django 5.2 on 2025-04-29 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_signup_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('a7b7982d-6340-43d7-b69d-abee676ac6f9'), primary_key=True, serialize=False),
        ),
    ]
