# Generated by Django 5.2 on 2025-05-01 14:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_signup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('e1d40700-4385-4e34-aff1-6b43ea8f7014'), primary_key=True, serialize=False),
        ),
    ]
