# Generated by Django 5.2 on 2025-05-01 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_signup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('7991ba39-319d-4db2-9b90-f3964bed2638'), primary_key=True, serialize=False),
        ),
    ]
